---
# tasks file for zabbix-mysql-agent
- name: install python3-PyMySQL
  yum:
    name: python3-PyMySQL
    state: present

- name: create zabbix user
  mysql_user:
    name: zabbix
    host: localhost
    password: "{{ zabbix_dbpass | default('dwRW2unMF&T', true) }}"
    priv: "*.*:process"
    state: present
    login_user: root
    login_password: "{{ db_passwd }}"
  ignore_errors: yes

- name: create dir
  file:
    path: /var/lib/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0755

- name: put my.cnf
  template:
    src: ../templates/my.cnf
    dest: /var/lib/zabbix/.my.cnf
    owner: zabbix
    group: zabbix
    mode: 0644
