---
- name: set kernel parameters to sysctl.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'net.ipv6.conf.all.disable_ipv6',value: '1' }
    - { name: 'net.ipv6.conf.default.disable_ipv6',value: '1' }

- name: remove docker package
  dnf:
    name: 
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: removed

- name: add docker repository
  shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker package
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - iproute-tc

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: deploy kubernetes.repo file
  template:
    src: ../templates/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: install docker package
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes

- name: mkdir /var/lib/kubelet
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "/var/lib/kubelet"
    - "/etc/systemd/system/kubelet.service.d"

- name: deploy config.yaml file
  template:
    src: ../templates/config.yaml
    dest: /var/lib/kubelet/config.yaml
    owner: root
    group: root
    mode: 0644

- name: deploy 20-extra-args.conf file
  template:
    src: ../templates/20-extra-args.conf
    dest: /etc/systemd/system/kubelet.service.d/20-extra-args.conf
    owner: root
    group: root
    mode: 0644

- name: start kubelet
  systemd:
    name: kubelet
    state: started
    daemon_reload: yes
    enabled: yes

- name: deploy containerd.conf file
  template:
    src: ../templates/containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    owner: root
    group: root
    mode: 0644

- name: modprobe overlay && modprobe br_netfilter
  shell: modprobe overlay && modprobe br_netfilter

- name: deploy k8s.conf file
  template:
    src: ../templates/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: sysctl --system
  shell: sysctl --system

- name: sed -i 's/disabled_plugins = \["cri"\]/disabled_plugins = \[""\]/' /etc/containerd/config.toml
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^disabled_plugins = \["cri"\]'
    line: 'disabled_plugins = [""]'
    backup: yes

- name: start containerd
  systemd:
    name: containerd
    state: started
    enabled: yes

- name: restart server
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: waiting for server
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=60
  become: false