---
# tasks file for logs/httpd
- name: put httpd logrotate file
  template:
    src: ../templates/{{ item }}
    dest: /etc/logrotate.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - httpd
