---
- name: configure epel exclude for zabbix
  ini_file:
    dest: /etc/yum.repos.d/epel.repo
    state: present
    section: epel
    option: excludepkgs
    value: 'zabbix*'

- name: install zabbix repository
  dnf:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: install zabbix package
  dnf:
    name:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-selinux-policy
      - zabbix-agent
      - zabbix-web-japanese
    state: present
    disable_gpg_check: yes

- name: create db for zabbix
  mysql_db:
    name: zabbix
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    encoding: utf8mb4
    collation: utf8mb4_bin

- name: create zabbix user
  mysql_user:
    name: zabbix
    host: localhost
    password: "{{ mysql_zabbix_password }}"
    priv: zabbix.*:all
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: set global log_bin_trust_function_creators = 1
  mysql_query:
    login_db: zabbix
    query: set global log_bin_trust_function_creators = 1;
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: check zabbix.db
  stat:
    path: /var/lib/mysql/zabbix/widget.ibd
  register: zabbix_db

- name: deploy db data
  shell: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -u zabbix --password="{{ mysql_zabbix_password }}" zabbix
  when: not zabbix_db.stat.exists

- name: set global log_bin_trust_function_creators = 0
  mysql_query:
    login_db: zabbix
    query: set global log_bin_trust_function_creators = 0;
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: systemctl restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted
    enabled: yes
    