---
# tasks file for nginx
- name: deploy nginx.repo
  template:
    src: "../templates/nginx.repo.j2"
    dest: "/etc/yum.repos.d/nginx.repo"
    owner: root
    group: root
    mode: 0644

- name: install nginx
  yum:
    name:
      - nginx
    enablerepo: nginx-stable

- name: put upstream.conf
  template:
    src: "../templates/{{ item }}"
    dest: /etc/nginx/conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - upstream.conf
    #- alb_backend.conf 

- name: change worker_connections
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: "worker_connections  1024;" ,line: "worker_connections  4096;" }

- name: change worker_rlimit_nofile
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    state: present
    insertafter: "^worker_processes  auto;"
    line: "worker_rlimit_nofile  4096;"

- name: change file descriptor limit for nginx
  template:
    src: "../templates/limits.conf"
    dest: "/etc/systemd/system/nginx.service.d/"
    owner: root
    group: root
    mode: 0644

- include_tasks: vhost.yml

- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes 

