---
- name: mkdir vhosts directory
  file:
    path: "/var/www/vhosts"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: domain_name is defined

- name: mkdir public_html directory
  file:
    path: "/var/www/vhosts/{{ item.domain }}/public_html"
    state: directory
    owner: "{{ item.customer }}"
    group: nginx
    mode: 02775
    recurse: yes
  when: domain_name is defined
  with_items:
    -  "{{ domain_name }}"

- name: add virtualhost
  template:
    src: "../templates/vhost.j2"
    dest: "/etc/nginx/conf.d/vhost.{{ item.domain }}.conf"
    owner: root
    group: root
    mode: 0644
  when: domain_name is defined
  with_items:
    -  "{{ domain_name }}"

- name: mkdir custom docment root
  file:
    path: "{{ item.document_root }}"
    state: directory
    owner: "{{ item.customer }}"
    group: nginx
    mode: 02775
    recurse: yes
  when: custom_domain is defined
  with_items:
    -  "{{ custom_domain }}"

- name: add custom virtualhost
  template:
    src: "../templates/custom_vhost.j2"
    dest: "/etc/nginx/conf.d/vhost.{{ item.domain }}.conf"
    owner: root
    group: root
    mode: 0644
  when: custom_domain is defined
  with_items:
    -  "{{ custom_domain }}"