---
# リポジトリ追加
- name: install epel and remi repository
  yum:
    name:
      - epel-release
      - https://rpms.remirepo.net/enterprise/remi-release-9.rpm
    disable_gpg_check: yes

# php インストール
- name: dnf module enable
  shell: "dnf module enable -y php:remi-{{ php_var | default('8.1', true) }}"

- name: install php-module
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_modules | default('php-fpm', true) }}"

# php.ini 変更
- name: change php.ini
  lineinfile:
    dest: /etc/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: ";date.timezone*" ,line: "date.timezone = Asia/Tokyo" }
    - { regexp: "expose_php = On" ,line: "expose_php = Off" }
    - { regexp: "post_max_size = 8M" ,line: "post_max_size = 128M" }
    - { regexp: "upload_max_filesize = 2M" ,line: "upload_max_filesize = 128M" }

# php-fpm ファイルの設置
- name: deploy web.conf 
  template:
    src: ../templates/www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
    backup: yes 

# キャッシュディレクトリ権限調整
- name: change permission
  file:
    path: /var/lib/php/{{ item }}
    owner: root
    group: "{{ webuser | default('nginx', true) }}"
    mode: 0770
  with_items:
    - opcache
    - session
    - wsdlcache

# php-fpm ファイルディスクリプタの上限値
- name: mkdir /etc/systemd/system/php-fpm.service.d/
  file:
    path: "/etc/systemd/system/php-fpm.service.d"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: change file descriptor limit for php-fpm
  template:
    src: "../templates/limits.conf"
    dest: "/etc/systemd/system/php-fpm.service.d/"
    owner: root
    group: root
    mode: 0644

# php-fpm 起動
- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted
    daemon_reload: yes
    enabled: yes
