---
- name: install zabbix repository
  dnf:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/9/x86_64/zabbix-release-5.0-3.el9.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: install zabbix-agent
  dnf:
    name: zabbix-agent
    state: present
    enablerepo: zabbix
    disablerepo: epel

- name: configure zabbix-agent.conf
  lineinfile:
    dest: "/etc/zabbix/zabbix_agentd.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "Server=127.0.0.1" ,line: "Server={{ zabbix_server_ip | default('127.0.0.1', true) }}" }
    - { regexp: "ServerActive=127.0.0.1" ,line: "ServerActive={{ zabbix_server_ip | default('127.0.0.1', true) }}" }
    - { regexp: "Hostname=Zabbix server" ,line:  "Hostname={{ inventory_hostname }}" }

- name: deploy userparam_memory.conf
  template:
    src: ../templates/userparam_memory.conf
    dest: /etc/zabbix/zabbix_agentd.d/
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: configure dnf exclude for zabbix updates
  lineinfile:
    path: /etc/dnf/dnf.conf
    regex: '^exclude=(.*)'
    line: 'exclude=\1 zabbix*'
    state: present