---
# zabbixエージェント導入
- name: zabbix-repo_add
  dnf:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/9/x86_64/zabbix-release-5.0-3.el9.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: zabbix-agent_install
  shell: "dnf install zabbix-agent --disablerepo=epel -y"

- name: zabbix-agent_conf_change
  lineinfile:
    dest: "/etc/zabbix/zabbix_agentd.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "Server=127.0.0.1" ,line: "Server={{ zabbix_server_ip | default('127.0.0.1', true) }}" }
    - { regexp: "ServerActive=127.0.0.1" ,line: "ServerActive={{ zabbix_server_ip | default('127.0.0.1', true) }}" }
    - { regexp: "Hostname=Zabbix server" ,line:  "Hostname={{ inventory_hostname }}" }

- name: deploy userparam_memory.conf
  template:
    src: ../templates/userparam_memory.conf
    dest: /etc/zabbix/zabbix_agentd.d/
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted
    daemon_reload: yes
    enabled: yes