---
# tasks file for mysql-server80

- name: install mysql80 repository
  shell: "dnf install https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm -y"

- name: install expect
  yum:
    name:
      - expect
      - python3-pip
    state: present

- name: pip install pexpect
  pip:
    name:
      - pexpect

- name: install mysql
  shell: "dnf install --disablerepo=appstream mysql-community-server -y"

- name: put my.cnf
  template:
    src: ../templates/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: mkdir /var/log/mysql/
  file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: 0755

- name: start mysql
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: confirm check_file
  stat: path=/usr/local/etc/mysql_stat.txt
  register: result_mysql_exit

- name: put mysql_secure_installation_script
  template:
    src: ../templates/mysql_secure_installation_script
    dest: /tmp/mysql_secure_installation_script
    owner: root
    group: root
    mode: 0755

- name: exec mysql_secure_installation_script
  shell: "/tmp/mysql_secure_installation_script"
  when: not result_mysql_exit.stat.exists

- name: create check_file
  file:
    path: /usr/local/etc/mysql_stat.txt
    state: touch
    mode: "u=rw,g=r,o=r"

- name: change error-log location
  lineinfile:
    dest: /etc/my.cnf
    state: present
    backrefs: yes
    regexp: '^log-error = /var/log/mysqld.log'
    line: 'log-error = /var/log/mysql/mysqld.log'
  notify: restart_mysqld_handler

- name: mkdir /etc/systemd/system/mysqld.service.d/
  file:
    path: "/etc/systemd/system/mysqld.service.d"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: change file descriptor limit for mysqld
  template:
    src: "../templates/limits.conf"
    dest: "/etc/systemd/system/mysqld.service.d/"
    owner: root
    group: root
    mode: 0644

- name: restart mysqld
  systemd:
    name: mysqld
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: mysql_config_editor print --login-path=lroot
  shell: mysql_config_editor print --login-path=lroot
  register: lroot
  changed_when: False

- name: mysql_config_editor set -G lroot -h localhost -u root -p
  expect:
    command: mysql_config_editor set -G lroot -h localhost -u root -p
    responses:
      "Enter password:": "{{ db_passwd }}"
  when: not 'lroot' in lroot.stdout