---
# リポジトリ追加
- name: install epel and remi repository
  yum:
    name:
      - epel-release
      - https://rpms.remirepo.net/enterprise/remi-release-9.rpm
    disable_gpg_check: yes

- name: dnf module enable
  shell: "dnf module enable -y php:remi-{{ php_var | default('8.1', true) }}"

- name: install php-module
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_modules | default('php', true) }}"

# php.ini 変更
- name: change php.ini
  lineinfile:
    dest: "/etc/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: ";date.timezone*" ,line: "date.timezone = Asia/Tokyo" }
    - { regexp: "expose_php = On" ,line: "expose_php = Off" }
    - { regexp: "post_max_size = 8M" ,line: "post_max_size = 128M" }
    - { regexp: "upload_max_filesize = 2M" ,line: "upload_max_filesize = 128M" }
