---
# tasks file for mysql-client
- name: install mysql80 repository
  shell: "dnf install https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm -y"
  
- name: install mysql
  shell: "dnf install --disablerepo=appstream mysql-community-client -y"
